### ISSUE TITLE
Use ShareLaTeX Cloud Compiler for PDFs

### ISSUE THREAD

**Issue by blipp** [fsphys/thesisvorlage-latex#2]
We could use the ShareLaTeX Cloud Compiler to generate all the PDFs. Then there would be no need to commit them. See https://www.sharelatex.com/github/
The same applies for https://github.com/fsphys/praktikum-protokollvorlage-latex , and it's maybe even more important there, as we have master, example and readme, all with PDFs in the repository.

**Comment by PhilippVerpoort** [comment]
Thanks for the idea. I already discussed this with Robin. I'm sorry, but I'm still not getting, how this is supposed to be useful. I think, it would be, if we were actually writing a report on GitHub. But we develop a template and when changes are applied, the PDFs have to be created on the computer and reviewed, anyway, in order to check that the applied changes are working. This is like writing C++ code and upload the code to git without checking whether the program would still compile with the new pieces of code. Don't you agree?
In addition, we would have to find out, which exact LaTeX packages the ShareLaTeX compiler is using. It could happen that changes on my local machine will work, but not on the ShareLaTeX compiler, simply because I use a different version of some package. I would prefer sticking to something well known, like TeXLive. Again, this would not be such a severe problem, if we were only modifying text in a report and not markup commands in a template.
